### ISSUE TITLE
Set-up travis

### ISSUE THREAD

**Issue by adamf321** [moxie-lean/lean-theme#14]

**Comment by adamf321** [comment]
@mitogh i think we still need .travis.yml... as this project is open source and in gh, we need travis to be able to build the project. BB pipelines will be used for private copies of this theme used in our projects.

**Comment by mitogh** [comment]
Okay makes sense, however I think we should draw a clear line of what the priority is: 

- Work smooth as much as possible for anyone.
- Work smooth as much as possible for us.

Because that moves the direction of some stuff on the theme, to me is better to make it work for anyone since `us` is just a subset of `anyone`

**Comment by adamf321** [comment]
Anyone is good... but only if it's not going to create a lot of extra work or make the theme less useful for us. We should discuss if we find any cases like this.
However, for this issue we need to travis file to preserve the integrity of this repo. We also need the bb file. Other people could add CircleCI or whatever other files if they want.
